### ISSUE TITLE
NoMethodError: undefined method `consolidate' for Logging:Module

### ISSUE THREAD

**Issue by halloffame** [effkay/blazing#85]
[Logging](https://rubygems.org/gems/logging) just got upgraded to v2.0.0, in the process they removed logger consolidation. https://github.com/TwP/logging/blob/logging-2.0.0/History.txt

Now I am getting this error:

    NoMethodError: undefined method `consolidate' for Logging:Module
    ~/.rvm/gems/ruby-2.1.4/gems/blazing-0.4.1/lib/blazing/logger.rb:29:in `<module:Logger>'
    ~/.rvm/gems/ruby-2.1.4/gems/blazing-0.4.1/lib/blazing/logger.rb:4:in `<module:Blazing>'
    ~/.rvm/gems/ruby-2.1.4/gems/blazing-0.4.1/lib/blazing/logger.rb:3:in `<top (required)>'
    ~/.rvm/gems/ruby-2.1.4/gems/blazing-0.4.1/lib/blazing.rb:1:in `require'
    ~/.rvm/gems/ruby-2.1.4/gems/blazing-0.4.1/lib/blazing.rb:1:in `<top (required)>'

**Comment by halloffame** [comment]
It looks like there is already a PR open for this issue. https://github.com/effkay/blazing/pull/84
